version: "3.9"
services:
  ##
  # DNS
  ##
  powerdns-db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pdns
      MYSQL_DATABASE: pdns
    networks:
      - dns-net
    volumes:
      - powerdns-db:/var/lib/mysql

  powerdns:
    build:
      context: ./dockers/powerdns
      args:
        - API_KEY=test
    ports:
      - "53:53"
      - "53:53/udp"
    depends_on:
      - powerdns-db
      - elasticsearch
    networks:
      - dns-net
      - elasticsearch-net

  ##
  # TRAEFIK
  ##
  redis:
    image: redis
    networks:
      - redis-net
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  traefik:
    image: traefik
    build:
      context: ./dockers/traefik

    ports:
      - "80:80"
      - "443:443"
      - "1337:1337"
    volumes:
      - traefik-data:/data:rw
    environment:
      PDNS_API_KEY: "test"
      PDNS_API_URL: "http://powerdns:8081/"

    depends_on:
      - redis
      - powerdns

    networks:
      - traefik
      - dns-net
      - redis-net

  ##
  # ELASTIC SEARCH
  ##
  elasticsearch:
    image: elasticsearch:7.12.1
    networks:
      - elasticsearch-net
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

##
# Manager
##
  manager:
    image: "manager"
    build:
      context: ./dockers/manager
    depends_on:
      - powerdns
      - redis
      - traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      PM_DISABLE_AUTH: 1
      PM_REDIS_HOST: "redis://redis"
      PM_TRAEFIK_HTTP_API: "http://traefik:8080/api"
      PM_TRAEFIK_REDIS_ROOT: "traefik"
      PM_POWERDNS_HTTP_API: "http://powerdns:8081"
      PM_POWERDNS_HTTP_API_KEY: "test"
      PM_ELASTIC_SEARCH_HTTP_API: "elasticsearch:9200"
    networks:
      - redis-net
      - dns-net
      - elasticsearch-net
      - traefik
###

volumes:
  elasticsearch-data:
  powerdns-db:
    name: powerdns-db
  redis-data:
  traefik-data:

networks:
  redis-net:
  dns-net:
  elasticsearch-net:
  traefik:
    name: traefik
