version: "3.9"
services:
##
# DNS
##      
  powerdns-db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pdns
      MYSQL_DATABASE: pdns
    networks:
      - manager-net
    volumes:
     - powerdns-db:/var/lib/mysql

  powerdns:
    build:
      context: ./dockers/powerdns
      args:
        - API_KEY=test
    environment:
      REDIS_URL: redis://redis/0
    ports:
      - "53:53"
      - "53:53/udp"
      - "8081:8081"
    depends_on:
      - powerdns-db
      
    networks:
      - manager-net
      - elasticsearch-net

##
# TRAEFIK
##      
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - manager-net
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  traefik:
    image: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.redis.endpoints=redis:6379"
      - "--providers.redis.rootkey=traefik"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.udp.address=:1337/udp"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    depends_on:
      - redis
      - powerdns
  
    networks:
      - traefik
      - manager-net
  elasticsearch:
    image: elasticsearch:7.12.1
    ports:
      - 9200:9200
      - 9300:9300

    networks:
      - elasticsearch-net
      
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      


##
# Manager
##      
  # manager:
  #   build:
  #     context: ./dockers/manager

  #   depends_on:
  #     - powerdns
  #     - redis
  #     - traefik
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #     - "/var/lib/docker/volumes:/var/lib/docker/volumes"

  #   ports:
  #     - 5000:5000
  #   networks:
  #     - manager-net

###

volumes:
  elasticsearch-data:
  powerdns-db:
    name: powerdns-db
  redis-data:

networks:
  manager-net:
  elasticsearch-net:
  traefik:
    name: traefik
