version: "3.9"
services:
  ##
  # DNS
  ##
  powerdns-db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pdns
      MYSQL_DATABASE: pdns
    networks:
      - dns-net
    volumes:
      - powerdns-db:/var/lib/mysql

  powerdns:
    build:
      context: ./dockers/powerdns
      args:
        - API_KEY=test
    ports:
      - "53:53"
      - "53:53/udp"
      - "8081:8081"
    environment:
      MYSQL_HOST: "powerdns-db"
      MYSQL_PASSWORD: "pdns"
      MYSQL_USER: "root"
      MYSQL_DATABASE: "pdns"
    depends_on:
      - powerdns-db
      - elasticsearch
    networks:
      - dns-net
      - elasticsearch-net
    volumes:
      - powerdns-logs:/logs/pdns

  ##
  # TRAEFIK
  ##
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis-net
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  traefik:
    container_name: traefik
    image: traefik
    build:
      context: ./dockers/traefik

    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "1337:1337"
    volumes:
      - traefik-data:/data:rw
      - traefik-logs:/logs/traefik
    environment:
      TRAEFIK_PROVIDERS_REDIS_ENDPOINTS: "redis:6379"
      TRAEFIK_PROVIDERS_REDIS_ROOTKEY: "traefik"
      PDNS_API_KEY: "test"
      PDNS_API_URL: "http://powerdns:8081/"

    depends_on:
      - redis
      - powerdns

    networks:
      - traefik
      - dns-net
      - redis-net

  ##
  # ELASTIC SEARCH
  ##
  elasticsearch:
    image: elasticsearch:7.12.1
    ports:
      - 9200:9200
    networks:
      - elasticsearch-net
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  filebeat:
    build:
      context: ./dockers/filebeat
    user: root
    depends_on:
      - elasticsearch
    networks:
      - elasticsearch-net
    volumes:
        - /var/lib/docker:/var/lib/docker:ro
        - /var/run/docker.sock:/var/run/docker.sock
        - powerdns-logs:/logs/pdns
        - traefik-logs:/logs/traefik
##
# Manager
##
# manager:
#   image: "manager"
#   build:
#     context: ./dockers/manager
#   depends_on:
#     - powerdns
#     - redis
#     - traefik
#   volumes:
#     - "/var/run/docker.sock:/var/run/docker.sock:ro"
#   environment:
#     PM_REDIS_HOST: "redis://redis"
#     PM_TRAEFIK_HTTP_API: "http://traefik:8080/api"
#     PM_TRAEFIK_REDIS_ROOT: "traefik"
#     PM_POWERDNS_HTTP_API: "http://powerdns:8081"
#     PM_POWERDNS_HTTP_API_KEY: "test"
#     PM_ELASTIC_SEARCH_HTTP_API: "127.0.0.1:9200"
#   ports:
#     - 5000:5000
#   networks:
#     - redis-net
#     - dns-net
#     - elasticsearch-net
#     - traefik
# ###

volumes:
  elasticsearch-data:
  powerdns-logs:
  powerdns-db:
    name: powerdns-db
  redis-data:
  traefik-data:
  traefik-logs:

networks:
  redis-net:
  dns-net:
  elasticsearch-net:
  traefik:
    name: traefik
