[tool.poetry]
name = "powerdns_to_redis"
version = "0.1.0"
description = "Read powerdns log from stdin and send them to redis"
authors = ["BitK <bitk@yeswehack.com>"]

[tool.poetry.dependencies]
python = "^3.9"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
