[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.http]
    address=":80"
  [entryPoints.manager]
    address=":1337"
  [entryPoints.https]
    address=":443"

[providers.file]
  filename = "/etc/traefik/dynamic_conf.toml"

[providers.redis]
  endpoints = "redis:6379"
  rootkey = "traefik"
[log]
  level = "DEBUG"
[accessLog]
  filePath = "/logs/traefik/traefik.json"
  format = "json"

[api]
  insecure = true
  dashboard = false


[certificatesResolvers]
  [certificatesResolvers.letsencrypt-staging-http]
    [certificatesResolvers.letsencrypt-staging-http.acme]
      email = "test@example.com"
      storage = "/data/acme.json"
      caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  
      [certificatesResolvers.lets-encrypt-http.acme.httpChallenge]
        entryPoint = "http"

  [certificatesResolvers.letsencrypt-staging-dns]
    [certificatesResolvers.letsencrypt-staging-dns.acme]
      email = "test@example.com"
      storage = "/data/acme.json"
      caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
      
      [certificatesResolvers.lets-encrypt-dns.acme.dnsChallenge]
        provider = "pdns"
        delayBeforeCheck = 5
